// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApiDayOne.Models;

public partial class Student
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? Age { get; set; }

    public string Address { get; set; }

    public string Image { get; set; }

    [ForeignKey("Department")]
    public int DepartmentId { get; set; }
    public virtual Department Department { get; set; }
}